# Copyright (c) Nebari Development Team.
# Distributed under the terms of the Modified BSD License.

name: default
channels:
  - conda-forge
dependencies:
  # general
  - pip

  # jupyterhub/jupyterlab
  - nb_conda_kernels
  - ipython > 7
  - jupyter-server-proxy
  - "jupyter_server>=2.4.0"
  - jupyterlab >=4
  - jupyter_client
  - jupyter_console
  - jupyterhub==3.1.1
  - nbconvert
  - nbval

  # jupyterlab extensions
  - dask_labextension >= 5.3.0
  - jupyterlab-git >=0.30.0
  - sidecar >=0.5.0
  - ipywidgets ==7.7.1
  - ipyleaflet >=0.13.5
  - pyviz_comms >=2.0.1
  - jupyter-resource-usage >=0.6.0
  - nbgitpuller
  - jupyterlab_code_formatter
  - jupyterlab-spellchecker >= 0.7.3

  # viz tools
  - param
  - python-graphviz
  - plotly >=5.0
  - ipympl
  - bokeh <3.0.0

  # testing, docs, linting
  - pytest
  - hypothesis
  - flake8
  - sphinx
  - pytest-cov
  - black
  - isort
  - importnb
  - git-lfs

  # JHub Apps dependencies
  - flask
  - plotlydash-tornado-cmd
  - bokeh-root-cmd
  - jhsingle-native-proxy
  - panel
  # - voila
  - dash
  - streamlit
  - traitlets

  - pip:
      # vscode jupyterlab launcher
      - git+https://github.com/betatim/vscode-binder
      - jupyterlab-conda-store==2023.9.1 
      # - jupyter-tensorboard
      # - jupyterlab_nvdashboard
      - argo-jupyter-scheduler==2023.7.1
      - gradio
      - git+https://github.com/nebari-dev/jhub-apps.git@fd5a71ccdcc625d3e4f894c9c506ebb6dce6f35a
      - jupyterlab_pioneer
