name: base
channels:
  - conda-forge
dependencies:
  - pip==21.1.2
  - jupyterhub==4.1.5
  - jupyterhub-kubespawner==4.2.0
  - oauthenticator==16.3.0
  - escapism==1.0.1
  - python-kubernetes
  - kubernetes_asyncio
  - jupyterhub-idle-culler==1.2.1
  - sqlalchemy==1.4.46
  - pip:
    - nebari-jupyterhub-theme
    - python-keycloak==0.26.1
    - jhub-apps==2024.4.1
